name: Pipeline Backoffice Website

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Retrieve environment variables from SSM
        run: |
          VITE_HOST_API=$(aws ssm get-parameter --name "/comidin-backoffice/VITE_HOST_API" --with-decryption --query "Parameter.Value" --output text)
          VITE_ASSETS_API=$(aws ssm get-parameter --name "/comidin-backoffice/VITE_ASSETS_API" --with-decryption --query "Parameter.Value" --output text)
          VITE_S3_ASSETS_AVATAR=$(aws ssm get-parameter --name "/comidin-backoffice/VITE_S3_ASSETS_AVATAR" --with-decryption --query "Parameter.Value" --output text)
          VITE_AWS_COGNITO_USER_POOL_ID=$(aws ssm get-parameter --name "/comidin-backoffice/VITE_AWS_COGNITO_USER_POOL_ID" --with-decryption --query "Parameter.Value" --output text)
          VITE_AWS_COGNITO_CLIENT_ID=$(aws ssm get-parameter --name "/comidin-backoffice/VITE_AWS_COGNITO_CLIENT_ID" --with-decryption --query "Parameter.Value" --output text)
          VITE_API_COMIDIN=$(aws ssm get-parameter --name "/comidin-backoffice/VITE_API_COMIDIN" --with-decryption --query "Parameter.Value" --output text)
          echo "VITE_HOST_API=$VITE_HOST_API" >> $GITHUB_ENV
          echo "VITE_ASSETS_API=$VITE_ASSETS_API" >> $GITHUB_ENV
          echo "VITE_S3_ASSETS_AVATAR=$VITE_S3_ASSETS_AVATAR" >> $GITHUB_ENV
          echo "VITE_AWS_COGNITO_USER_POOL_ID=$VITE_AWS_COGNITO_USER_POOL_ID" >> $GITHUB_ENV
          echo "VITE_AWS_COGNITO_CLIENT_ID=$VITE_AWS_COGNITO_CLIENT_ID" >> $GITHUB_ENV

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: List contents of dist directory
        run: |
          echo "Listing contents of dist directory:"
          ls 

      - name: Deploy to AWS S3
        run: |
          aws s3 sync dist/ s3://comidin.com.ar --delete
